spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/spring_boot_learn?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&useSSL=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      initialSize : 3
      maxActive: 15
      maxIdle: 15
      minIdle: 3
      test-while-idle: true
      validation-query: select 1 from dual
      validation-interval: 60000
      time-between-eviction-runs-millis: 60000
    slave:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/spring_boot_learn_2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&useSSL=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      initialSize : 3
      maxActive: 15
      maxIdle: 15
      minIdle: 3
      test-while-idle: true
      validation-query: select 1 from dual
      validation-interval: 60000
      time-between-eviction-runs-millis: 60000
  jpa:
    show-sql: true






